twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    default_config: default
    configs:
        default:
            toolbar:
              - ['Bold', 'Italic', 'Link', 'BulletedList', 'NumberedList', 'Image']
            removeButtons: 'NewPage,Preview,Print,Templates, '
