vich_uploader:
    db_driver: orm

    mappings:
        property_images:
            uri_prefix: images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update:   true
            delete_on_remove:   true
            inject_on_load: false

        id_card:
            uri_prefix: 'uploads/id_card'
            upload_destination: '%kernel.project_dir%/public/uploads/id_card'
        tax_form:
            uri_prefix: 'uploads/tax_form'
            upload_destination: '%kernel.project_dir%/public/uploads/tax_form'
        pay_stub:
            uri_prefix: 'uploads/pay_stub'
            upload_destination: '%kernel.project_dir%/public/uploads/pay_stub'
        proof_residence:
            uri_prefix: 'uploads/proof_residence'
            upload_destination: '%kernel.project_dir%/public/uploads/proof_residence'
        guarantor_pay_stub:
            uri_prefix: 'uploads/guarantor_pay_stub'
            upload_destination: '%kernel.project_dir%/public/uploads/guarantor_pay_stub'