vich_uploader:
    db_driver: orm
    mappings:
        property_images:
            uri_prefix: '/images/properties'
            upload_destination: '%kernel.project_dir%/public/images/properties'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false

        id_card_recto:
            uri_prefix: '/uploads/id_card_recto'
            upload_destination: '%kernel.project_dir%/public/uploads/id_card_recto'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false

        id_card_verso:
            uri_prefix: '/uploads/id_card_verso'
            upload_destination: '%kernel.project_dir%/public/uploads/id_card_verso'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false

        taxForm:
            uri_prefix: '/uploads/tax_form'
            upload_destination: '%kernel.project_dir%/public/uploads/tax_form'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false

        pay_stub_1:
            uri_prefix: '/uploads/pay_stub1'
            upload_destination: '%kernel.project_dir%/public/uploads/pay_stub1'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false

        pay_stub_2:
            uri_prefix: '/uploads/pay_stub2'
            upload_destination: '%kernel.project_dir%/public/uploads/pay_stub2'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false

        pay_stub_3:
            uri_prefix: '/uploads/pay_stub3'
            upload_destination: '%kernel.project_dir%/public/uploads/pay_stub3'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false

        proof_residence:
            uri_prefix: '/uploads/proof_residence'
            upload_destination: '%kernel.project_dir%/public/uploads/proof_residence'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false

        guarantor_pay_stub_1:
            uri_prefix: '/uploads/guarantor_pay_stub1'
            upload_destination: '%kernel.project_dir%/public/uploads/guarantor_pay_stub1'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false

        guarantor_pay_stub_2:
            uri_prefix: '/uploads/guarantor_pay_stub2'
            upload_destination: '%kernel.project_dir%/public/uploads/guarantor_pay_stub2'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false

        guarantor_pay_stub_3:
            uri_prefix: '/uploads/guarantor_pay_stub3'
            upload_destination: '%kernel.project_dir%/public/uploads/guarantor_pay_stub3'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false