vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update:   true
            delete_on_remove:   true